$schema: "http://json.schemastore.org/buildkite"
steps:
  - label: ":bazel: Build and Test"
    agents:
      queue: bazel
    key: build
    command: |
      # Keep this link in sync with Development.md
      wget -L https://github.com/bazelbuild/buildtools/releases/download/6.0.0/buildifier-linux-amd64 -O buildifier
      chmod +x buildifier
      mv buildifier /usr/local/bin/

      # Bazel handles the C++ toolchain
      bazel build @llvm_toolchain//:clang-format

      # Lint the python code
      bazel build //tools:check

      bazel build //... --config=ci

      # Don't use //... as that will also try to update snapshots
      bazel test //test --test_output=errors --config=ci
